### ISSUE TITLE
Error building on MacOS 10.15.6 

### ISSUE THREAD

**Issue by ValerioParisMitritsakis** [built1n/rastercarve-preview#1]
I get the following error:

rastercarve-preview/libfml/src/vec2.cpp:76:9: error: use of undeclared identifier 'sincos';
      did you mean '__sincos'?
        sincos(angle, &s, &c);
        ^~~~~~
        __sincos
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/math.h:655:29: note: 
      '__sincos' declared here
__header_always_inline void __sincos(double __x, double *__sinp, double *__cosp) {
                            ^
1 error generated.
make[2]: *** [libfml/CMakeFiles/fml.dir/src/vec2.cpp.o] Error 1
make[1]: *** [libfml/CMakeFiles/fml.dir/all] Error 2
make: *** [all] Error 2

**Comment by built1n** [comment]
Fixed in 28078c7.
